[server]
maxuploadSize=15
enableXsrfProtection = false

[theme] #You have to add this line

primaryColor= '#0E8388'

backgroundColor= '#2C3333'

SecondaryBackgroundColor = '#2E4F4F'

textColor = "CBE4DE"

font = "monospace"

[global]

showWarningOnDirectExecution = false
[client]
showErrorDetails = false